CONFIG_MODE_ON = "~M00910001." 
OUTPUT_CONFIG = "~M00510000."    
SAVE_CONFIG = "~MA5F0506A."      
CONFIG_MODE_OFF = "~M00910000."  
SET_DELAY = "~M00B0000A."        

CONFIG_SEQUENCE = [
    CONFIG_MODE_ON,
    OUTPUT_CONFIG,
    SET_DELAY,
    SAVE_CONFIG,
    CONFIG_MODE_OFF,
]

TRIGGER_SCAN = "SCAN"  
STOP_SCAN = "STOP"
STATUS_CHECK = "STATUS"